# Site settings
title: Zach Chan's Blog
author: Zach Chan
author_avatar: /images/header.jpg
email: me@zachchan.com
description: 生命不止，折腾不息 
url: "https://blog.zachchan.com"
domain: ""
github_username: zach-c
github_site_repo: zach-c/dongyado.github.io
disqus: monsterslayer


# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    syntax_highlighter: rouge
    extensions: ["fenced_code_blocks", "autolink", "tables", "smart"]

sass:
    style: :compressed
    sass_dir: _sass

permalink: pretty
excerpt_separator: "<!-- more -->"

# path
categories_path: categories/
tags_path: tags/


gems:
  - jekyll-sitemap
